# Generated by Django 5.2.4 on 2025-08-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiantoursagency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('economic', 'Economic'), ('moderate', 'Moderate'), ('luxury', 'Luxury')], default='moderate', max_length=10),
        ),
    ]
