# Generated by Django 5.2.4 on 2025-08-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiantoursagency', '0002_tour_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='orgin_country',
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(default='Experience the best of your destination with our exclusive tour package.'),
        ),
        migrations.AddField(
            model_name='tour',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='image_url',
            field=models.URLField(default='https://source.unsplash.com/random/800x600/?vacation'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_hot_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='origin_country',
            field=models.CharField(default='India', max_length=64),
        ),
        migrations.AddField(
            model_name='tour',
            name='title',
            field=models.CharField(default='Amazing Tour Package', max_length=200),
        ),
    ]
